# Number of cell's to return morpholgy metrics, set to 0 to retrieve all cell's
uint32 max_cells

# Picture
sensor_msgs/Image image # Must be in RGB format

# Dish parameters
bool mask_petri_dish    # True  = mask image to contain only the petri dish
float32 dish_diameter    # For detecting circle-like object by canny method [pixel]
float32 dish_offset      # Reduce dish_diameter by this offset when applying the mask [pixel]

# Compute cell quality metric, set to zero to disable given metric
#
#   Cell Quality = (weight * area +
#                   weight * compactness +
#                   weight * eccentricity +
#                   weight * nn_collision_distance +
#                   weight * solidity) / 5.0
#
#   1. Metrics are normalized
#
float32 weight_area                     # Area of the region i.e. number of pixels of the region scaled by pixel-area
float32 weight_compactness              # Ratio of the area of an object to the area of a circle with the same perimeter
float32 weight_eccentricity             # Eccentricity of the ellipse that has the same second-moments as the region
float32 weight_nn_collision_distance    # Nearest neighbor distance [pixel]
float32 weight_solidity                 # Ratio of pixels in the region to pixels of the convex hull image

# nearest neighbor
uint32 nn_query_size    # Return X nearest neighbor's from the centroid tree query, min = 1
                        # A higher number will lead to a better aproximation of the collision distance


# Discard cells based on Threshold, set to 0 to disable
float32 cell_min_diameter        # discard if < min_diameter [pixel]
float32 cell_max_diameter        # discard if > max_diameter [pixel]
float32 cell_min_compactness    # discard if < min_compactness [pixel]
float32 cell_min_solidity       # discard if < min_solidity [pixel]
float32 cell_max_eccentricity   # discard if > max_eccentricity [pixel]

# Discard cells based on Statistics, set to 0 to disable
# The mean and std are computed on non discarded cell's (after passing through the Threshold filtering)
float64 std_weight_diameter # 1 = Keep 68.27% of cell's between mu -1*sigma and mu + 1*sigma
                            # 2 = Keep 95.45% of cell's between mu -2*sigma and mu + 2*sigma
                            # 3 = Keep 99.73% of cell's between mu -3*sigma and mu + 3*sigma

# Send back extra data
bool send_image_result

# Debugging
bool verbose                    # output log from colony_morphology library
string save_path                # absolute path to save files to, e.g. "/home/user/mydirectory"
bool save_circle_detection      # subplot of circle detection algorithm [png]
bool save_segmentation_process  # subplot of all the segmentation (after circle detection) [png]
bool save_cell_annotation       # annotated cell wrt. the cell_quality metric [png]
bool save_properties            # metrics of region properties [xlsx]

bool plot_interactive_properties  # plot cell properties on a web client, web page will open automatically

---

sensor_msgs/Image image_result      # populated only if requested

ColonyMetrics[] cell_metrics        # cell's metrics in order, highest cell quality to lowest
